# Generated by Django 4.2.23 on 2025-07-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
