# Generated by Django 4.2.23 on 2025-07-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0002_job_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
